DROP TABLE IF EXISTS Car;
DROP TABLE IF EXISTS Brand;
DROP TABLE IF EXISTS Model;
DROP TABLE IF EXISTS Color;

DROP SEQUENCE IF EXISTS CAR_SEQ;
DROP SEQUENCE IF EXISTS BRAND_SEQ;
DROP SEQUENCE IF EXISTS MODEL_SEQ;
DROP SEQUENCE IF EXISTS COLOR_SEQ;

CREATE TABLE Car (
  ID INTEGER NOT NULL,
  ITEM_REF VARCHAR(60) NOT NULL,
  BRAND_ID INTEGER NOT NULL,
  MODEL_ID INTEGER NOT NULL,
  COLOR_ID INTEGER NOT NULL,
  SCALE VARCHAR(100),
  LIMITED_EDITION SMALLINT,
  COUPE BOOLEAN,
  BOXED BOOLEAN,
  CREATED_ON TIMESTAMP NULL DEFAULT NULL,
  LASTMODIFIED_ON TIMESTAMP NULL DEFAULT NULL,
  VERSION BIGINT,
  PRIMARY KEY(ID)
);

CREATE SEQUENCE CAR_SEQ START WITH 1;
CREATE INDEX idx_item_ref ON Car (ITEM_REF);
CREATE INDEX idx_brand ON Car (BRAND_ID);
CREATE INDEX idx_color ON Car (COLOR_ID);

CREATE TABLE Brand (
  ID INTEGER NOT NULL,
  NAME VARCHAR(120) NOT NULL,
  CREATED_ON TIMESTAMP NULL DEFAULT NULL,
  LASTMODIFIED_ON TIMESTAMP NULL DEFAULT NULL,
  VERSION BIGINT,
  PRIMARY KEY(ID),
  UNIQUE (NAME)
);

CREATE SEQUENCE BRAND_SEQ START WITH 1;

CREATE TABLE Color (
  ID INTEGER NOT NULL,
  NAME VARCHAR(120) NOT NULL,
  CREATED_ON TIMESTAMP NULL DEFAULT NULL,
  LASTMODIFIED_ON TIMESTAMP NULL DEFAULT NULL,
  VERSION BIGINT,
  PRIMARY KEY(ID),
  UNIQUE (NAME)
);

CREATE SEQUENCE COLOR_SEQ START WITH 1;

CREATE TABLE Model (
  ID INTEGER NOT NULL,
  BRAND_ID INTEGER NOT NULL,
  TYPE VARCHAR(120) NOT NULL,
  NAME VARCHAR(120) NOT NULL,
  PRODUCTION_DATE TIMESTAMP,
  CREATED_ON TIMESTAMP NULL DEFAULT NULL,
  LASTMODIFIED_ON TIMESTAMP NULL DEFAULT NULL,
  VERSION BIGINT,
  PRIMARY KEY(ID),
  UNIQUE (BRAND_ID, TYPE)
);

CREATE SEQUENCE MODEL_SEQ START WITH 1;